### PR TITLE
Issue 152: The G Pro keyboard lacks dedicated multimedia keys.

### PR DESCRIPTION
**Pull request by DanEble**
Ignore the "multimedia" key group and omit it from the help text.

### CODE REVIEW

**Comment by MatMoul** [comment]
I just looked at your code and overall, it's good.
I saw that you removed the multimedia keys from the g410, g513 and g610.
Are you sure that the g610 does not have a multimedia key, if so, correct the help file, otherwise move it with the g810 ...
I will thank you if you can reindent the g513 and add it in the help.h file with the following line:
`g513 = rgb | commit | numpad | setall | setgroup | setkey | setindicators | poweronfx,`

**Comment by DanEble** [comment]
Oops.  I didn't mean to remove multimedia support from those other keyboards; I was just not thinking clearly.  I will correct it.

**Comment by MatMoul** [comment]
No problem, looking picture on GG of g410 and g513 show that has the same mixed multimedia keys than the G Pro...

**Comment by MatMoul** [comment]
@DanEble Perfect, thank you

**Pull request merged**
