### PR TITLE
Add support for g512

### PR DESCRIPTION
**Pull request by pfsmorigo**
I recently bought a G512 and fixed the support for it

### CODE REVIEW

**Comment by stokbox** [comment]
Tested and fully working on my end (with my brand new G512 fr_FR layout)

**Comment by Cinux90** [comment]
Buy also a G512.
I'm waiting for the merge. :)

**Comment by malagant** [comment]
Any news on when this will be merged?

**Comment by Ayanrocks** [comment]
Please merge this

**Comment by MatMoul** [comment]
Coming soon...

**Pull request merged**
