### PR TITLE
Issue #158: Add "waves" effect found on G Pro

### PR DESCRIPTION
**Pull request by DanEble**

### CODE REVIEW

**Comment by MatMoul** [comment]
Speed add but hard changes...
I need to test the change before comment or merge it

**Comment by MatMoul** [comment]
I don't have fully digest your changes but it seem to work ;-)

**Comment by MatMoul** [comment]
Yea, checked the waves effect on my g810 and it work...

**Comment by MatMoul** [comment]
Ok it's accepted but remove the spaces on [lines 67,69,71](https://github.com/DanEble/g810-led/blob/issue-158-add-waves-effect/src/classes/Keyboard.h#L67) in src/classes/Keyboard.h

**Comment by DanEble** [comment]
Thank you for your responsiveness as a reviewer.  I have removed those blank lines.

To explain the changes a bit, I added the NativeEffectGroup enum to describe the values used in byte 5 of the USB message that sets the native effect.  That byte takes the value 4 for all of the known wave variations.

I packed a NativeEffectGroup value into the NativeEffect enum values following the precedent of the KeyAddressGroup and Key enums.  In a project of my own, I would probably have chosen to use a mapping function, e.g. `effectGroup = toNativeEffectGroup(effect)`, rather than complicate the enum definitions and require overt casting, but I thought that consistency in with existing code was more valuable.

**Comment by MatMoul** [comment]
good work

**Pull request merged**
