### PR TITLE
Issue #157: -fx-store sets user-stored lighting

### PR DESCRIPTION
**Pull request by DanEble**
This is the last PR of my vacation. 😞😃

### CODE REVIEW

**Comment by MatMoul** [comment]
It's not vacation, you're worked hard these last days...
I just tested with my g810-led and it seem that Light+7 doesn't work...
I'll try to make more tests

**Comment by MatMoul** [comment]
I've tryied `g810-led -fx-store breathing all 00ff00 20s`
It set just the effect...

**Comment by DanEble** [comment]
If you also set the startup effect to wave and then disconnect and reconnect your keyboard, does it do wave or breathing?

**Comment by MatMoul** [comment]
Light+7 is not usable on g810, when I press it, the result is same as pressing the light key

**Comment by MatMoul** [comment]
After disabling udev, I run 
`g810-led --startup-mode wave`
disconnect and reconnect, I've wave effect. And then
`g810-led --startup-mode color`
disconnect and reconnect, I've cyan color.
But when I press Light+7, the Light key doesn't work as the same way as Light+6
This feature seem restricted to some keyboard or firmware...
I've not updated my keyboard for 2 or 3 years

**Comment by MatMoul** [comment]
I try to update my firmware

**Comment by DanEble** [comment]
Thanks for testing.  When I have time, I will rework this change so that -fx-store is described in the help text of gpro-led only.

**Comment by MatMoul** [comment]
I sugest to exclude the g810 but not the other keyboards...
And just waiting return from users...

**Comment by DanEble** [comment]
I updated the help.

**Comment by MatMoul** [comment]
Thanks for all your work and good luck for this new year

**Pull request merged**
