### PR TITLE
Improve makefile

### PR DESCRIPTION
**Pull request by lynix**
Hi MatMoul,

thank you very much for your work, I really appreciate the new C++ version! :)
I've done some streamlining work on your makefile, feel free include my changes if you like them.

Best regards

lynix

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks, my make file was minimal...
Good work

**Comment by MatMoul** [comment]
Because you're best as me for makefile ;-p

Now we need a make install...

With creation of the boot and reboot unit, the udev rule and copy sample profiles to /etc/g810

**Comment by MatMoul** [comment]
And copy g810-led to /usr/bin

**Comment by MatMoul** [comment]
Just a small problem on makefile in the CFLAGS var... (-02) dont work on my ArchLinux...
When I use "g810-led -a ff0000", some keys it's not defined,

**Comment by lynix** [comment]
Well, this is not an OS issue (I'm on Arch as well, by the way ;) ) but rather bugs in the code.

In Keyboard.cpp for some reason you're always off by one byte when allocating the data arrays for the USB payload - see lines 446, 455, 481, 508 and 512.

E.g. (Keyboard.cpp, lines 445 ff)
```
data_size = 20;
data = new unsigned char[data_size - 1];
```
This creates an array of size 19, but some lines below there is
```
for(int i = 12; i < data_size; i++) data[i] = 0x00;
```
In the last iteration we got `i = (data_size - 1) = 19`, which makes `data[i]` an out-of-bounds access.

I'm sorry I can't test the fix (which would be removing all the ' -1' from array allocators) right now as I currently don't have a compiler with me :)

**Comment by MatMoul** [comment]
It seems that you're right for the array, need change this ...

Just for information, I have improved the function setkeys in keyboard.cpp ...
The definition is now done by blocks of 12 keys at once ...
The entire keyboard is defined in less than 200ms

**Comment by MatMoul** [comment]
Seem to be a linked problem : https://github.com/MatMoul/g810-led/issues/2

**Pull request merged**
