### PR TITLE
Support specifying a specific device for executing commands

### PR DESCRIPTION
**Pull request by pearsonk**
This adds support in the library and application for specifying a particular device for executing LED commands. It also organizes devices into a maintained structure that can be queried to determine which device would be found, mostly useful when the device is not explicitly specified.

Changes spread across 3 commits:
- library changes in Keyboard.c/Keyboard.h
- A new utility function for parsing uint16_t from a string, to map IDs
- Application changes to include new argument parsing and specifying devices by vendor, device, or serial

More specific changes listed in the commit logs themselves.

### CODE REVIEW

**Comment by MatMoul** [comment]
@pearsonk You'r very speed...
Your work is very well...
Just let me the time to study your changes

**Comment by MatMoul** [comment]
Works well
Just a question on the line 8 of th Keyboard.cpp, not sure, but "locale" seam not used

**Comment by MatMoul** [comment]
Another remark in main.cpp, it would be nice to init kbd only if required.
I lost 20ms when I call --help

**Comment by pearsonk** [comment]
<locale> is necessary for the wchar_t to char conversion (mbstowcs and wcstombs). The size differences makes a simple explicit casting unsafe, but the locale-provided functions provide necessary translations.

It makes sense to re-order the arguments and place the --help* before keyboard initialization, and anything else that may not require the specific device. I will amend the PR.

**Comment by pearsonk** [comment]
Commit to rearrange the help parsing is pushed.

**Comment by MatMoul** [comment]
Excellent

**Pull request merged**
