### PR TITLE
Add systemd resume service

### PR DESCRIPTION
**Pull request by sebschlicht**
This pull request adds a systemd service to enable g810-led with the default profile on resume.
The makefile has been updated to take account of the service file in both install and uninstall procedures.

The service file has been tested on Ubuntu 16.04 LTS.

Furthermore, I've found a minor error in the uninstall procedure in the makefile that (alone) prevents it from uninstalling correctly but I'll open another pull-request in this matter.

### CODE REVIEW

**Comment by sebschlicht** [comment]
The mentioned pull request to fix the makefile is #150.

**Comment by sebschlicht** [comment]
The fix is now part of this pull request, as well. Not what I intended to do but more convenient *if* you choose to merge this pull request. I leave #150 in place, in case you choose not to.

**Comment by MatMoul** [comment]
Hi and thank you for your PR, but I'm not sure that this service is required for the resume.
I've just tested on my computer and my keyboard is set after the resume without this service.
Are you using the udev rules ?

**Comment by sebschlicht** [comment]
Hey and thank you for maintaining this piece of software, at first!

I've just installed `g810-led` using the installation instructions, it's unclear to me whether this would enable these udev rules or not. According to the makefile I'd say it would, so the answer might be 'yes'.

I'll check if the rules match my G910 after christmas, chance are my german version is slightly different from what has been added to the rules so far.

**Comment by MatMoul** [comment]
@sebschlicht Closing because no feedback, you can reopen it if you want

**Pull request closed without merging**
