### PR TITLE
Implement device IO as a shared library

### PR DESCRIPTION
**Pull request by pearsonk**
Provide make targets and build configuration to create a shared object
for other systems/applications to use to control keyboard LEDs without
 the need for instantiating the g810-led process.

Provide make targets for installing library and development files into
environments, such as the current system or package builders.

Currently preserves precious behavior of building g810-led binary as
statically linked. Provides an alternative build target of "bin-linked"
which will create a dynamically linked variant.

Signed-off-by: Kevin Pearson <pearson.kevin.m@gmail.com>

### CODE REVIEW

**Comment by MatMoul** [comment]
It seem be good...

But I just have two observations and one question...
- Line 11 and 19 seem to be duplicate...
- After the line 47, in make clean, It would be nice to add @rm -rf lib
- And how to set MAJOR, MINOR and MICRO version ?

**Comment by pearsonk** [comment]
Ah, good catch. That was a casualty of a manual conflict resolution when rebasing upon master. I have rolled up the missed lines and added the libdir cleanup

**Comment by pearsonk** [comment]
MAJOR, MINOR, and MICRO are now defined under the program and version information section, largely created to match the tags used.

**Comment by MatMoul** [comment]
Thank you, I have merged your PR in the develop branch.
Just wait the next release

**Comment by TheZoreil** [comment]
Hi MatMoul, project realy interesting! I have a question about a G410. I can already control the color of LEDs (all LEDs of the keyboard of a single block), and make wave using the NativeEffect but I can not manage to control a single led ... Could you help me  by pointing to the structure of DATA please?

`Libusb_control_transfer(dev, 0x21, 0x09, 0x0211, 1, data, sizeof (data), 2000);`

` DATA [ ] = { 0x12, 0xff, 0x0c, 0x3a, 
                            0x00, 0x01, 0x00, 0x0e,
                            KEY, RED, GREEN, BLEU, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00,
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, 
                            0x00, 0x00, 0x00, 0x00, };`


thank you very much

P.S: I am French like you if you prefer to answer in French

**Comment by MatMoul** [comment]
@TheZoreil Please, open a new issue for your question, I can help you but these comments are for the PR

**Pull request merged**
